version: '3'

services:

  logs: &logs-template
    image: alpine
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    <<: *logs-template
    container_name: web_django
    build: ./docker/django
    ports:
      - 80:5000
    volumes:
    - ./src:/src

  pg:
    <<: *logs-template
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_USER=pguser
      - POSTGRES_DB=my_db
    ports:
      - 5432:5432
    volumes:
    - ./db/pg:/var/lib/postgresql/data
